# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14.16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm test
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: postgres
        PGHOST: postgres
        SECRET: githubactions
        PORT: 3000
    - run: npm run coverage
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: postgres
        PGHOST: postgres
        SECRET: githubactions
        PORT: 3000
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: npm i -g codecov && npm run coverage:report && codecov -t ${{ secrets.CODECOV_TOKEN }}